### ISSUE TITLE
What SW1 does is

### ISSUE THREAD

**Issue by duoffice** [HDR/MBC5-Flashcart#4]
Hello, what is the function of the switch? SW1, thank you

**Comment by HDR** [comment]
With 4MB flash you can use the switch to either have 2 2MB ROM's or a 4MB ROM

**Comment by duoffice** [comment]
Do you mean that if I use 4M flash, I can use one game card as two cards by switching between BankA and BankB? If I use Flash 2M or below, the switch doesn't make sense, right? thank you

**Comment by HDR** [comment]
Yes, you can flash 2 separate games @ 2MB or less to the cartridge if it has a 4MB chip, but the FRAM will be shared between the two.
